# The Site Configuration

# Import the theme
theme: jekyll-theme-chirpy

# The language of the webpage
lang: en

# Change to your timezone
timezone: Asia/Ho_Chi_Minh

# jekyll-seo-tag settings
title: CyberSec Notes
tagline: "Writeups, Pentest, Red Team, SOC Analyst, Blue Team"
description: "CTF writeup, Red Team, Blue Team fundamentals."

# Fill in the protocol & hostname for your site.
url: "https://mrdarkroot.github.io"

# ⚠️ Vì repo của bạn là MrDarkRoot/DuyTran.github.io nên phải có baseurl
baseurl: "/DuyTran.github.io"

github:
  username: "MrDarkRoot"

twitter:
  username: ""

social:
  name: "Duy Tran"
  email: "duyytrann22@gmail.com"
  bio: "Jr. Penetration Tester | Cyber Security Enthusiast"
  links:
    - "https://github.com/MrDarkRoot"
    - "https://twitter.com/username"

# Site Verification Settings
webmaster_verifications:
  google: ""
  bing: ""
  alexa: ""
  yandex: ""
  baidu: ""
  facebook: ""

# Web Analytics Settings
analytics:
  google:
    id: ""
  goatcounter:
    id: ""
  umami:
    id: ""
    domain: ""
  matomo:
    id: ""
    domain: ""
  cloudflare:
    id: ""
  fathom:
    id: ""

# Page views settings
pageviews:
  provider: ""

# Prefer color scheme setting
theme_mode: ""

# The CDN endpoint for media resources
cdn: ""

# the avatar on sidebar, support local or CORS resources
avatar: ""

# The URL of the site-wide social preview image used in SEO
social_preview_image: ""

# boolean type, the global switch for TOC in posts
toc: true

comments:
  provider: false
  disqus:
    shortname: ""
  utterances:
    repo: ""
    issue_term: ""
  giscus:
    repo: ""
    repo_id: ""
    category: ""
    category_id: ""
    mapping: ""
    strict: ""
    input_position: ""
    lang: ""
    reactions_enabled: ""

# Self-hosted static assets
assets:
  self_host:
    enabled: false
    env: ""

pwa:
  enabled: true
  cache:
    enabled: true
    deny_paths: []

paginate: 10

kramdown:
  footnote_backlink: "&#8617;&#xfe0e;"
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: highlight
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1

collections:
  tabs:
    output: true
    sort_by: order

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: post
      comments: true
      toc: true
      permalink: /posts/:title/
  - scope:
      path: _drafts
    values:
      comments: false
  - scope:
      path: ""
      type: tabs
    values:
      layout: page
      permalink: /:title/

sass:
  style: compressed

compress_html:
  clippings: all
  comments: all
  endings: all
  profile: false
  blanklines: false
  ignore:
    envs: [development]

exclude:
  - "*.gem"
  - "*.gemspec"
  - docs
  - tools
  - README.md
  - LICENSE
  - purgecss.js
  - "*.config.js"
  - "package*.json"

jekyll-archives:
  enabled: [categories, tags]
  layouts:
    category: category
    tag: tag
  permalinks:
    tag: /tags/:name/
    category: /categories/:name/
