theme: jekyll-theme-chirpy
lang: en
timezone: Asia/Ho_Chi_Minh

title: CyberSec Notes
tagline: "Writeups, Pentest, Red Team, SOC Analyst, Blue Team"
description: "CTF writeup, Red Team, Blue Team fundamentals."
url: "https://DuyTran.github.io"

github:
  username: "MrDarkRoot"   # Use your actual GitHub username

twitter:
  username: ""             # Leave blank if not used

social:
  name: "Duy Tran"
  email: "duyytrann22@gmail.com"
  bio: "Jr. Penetration Tester | Cyber Security Enthusiast"
  links:
    - "https://twitter.com/username"
    - "https://github.com/MrDarkRoot"

webmaster_verifications:
  google: ""
  bing: ""
  alexa: ""
  yandex: ""
  baidu: ""
  facebook: ""

analytics:
  google:
    id: ""
  goatcounter:
    id: ""
  umami:
    id: ""
    domain: ""
  matomo:
    id: ""
    domain: ""
  cloudflare:
    id: ""
  fathom:
    id: ""

pageviews:
  provider: ""

theme_mode: "" # [light | dark] or leave empty

cdn: ""

avatar: ""

social_preview_image: ""

toc: true

comments:
  provider: ""
  disqus:
    shortname: ""
  utterances:
    repo: ""
    issue_term: ""
  giscus:
    repo: ""
    repo_id: ""
    category: ""
    category_id: ""
    mapping: ""
    strict: ""
    input_position: ""
    lang: ""
    reactions_enabled: ""

assets:
  self_host:
    enabled: ""
    env: ""

pwa:
  enabled: true
  cache:
    enabled: true
    deny_paths: []

paginate: 10
baseurl: ""
